[I 2024-04-19 16:07:04.420 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-04-19 16:07:04.423 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-04-19 16:07:04.426 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-04-19 16:07:04.429 ServerApp] notebook | extension was successfully linked.
[I 2024-04-19 16:07:04.973 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-04-19 16:07:05.316 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-04-19 16:07:05.318 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-04-19 16:07:05.318 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-04-19 16:07:05.328 LabApp] JupyterLab extension loaded from /home/mihirban/miniconda3/lib/python3.11/site-packages/jupyterlab
[I 2024-04-19 16:07:05.328 LabApp] JupyterLab application directory is /home/mihirban/miniconda3/share/jupyter/lab
[I 2024-04-19 16:07:05.329 LabApp] Extension Manager is 'pypi'.
[I 2024-04-19 16:07:05.339 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-04-19 16:07:05.342 ServerApp] notebook | extension was successfully loaded.
[I 2024-04-19 16:07:05.343 ServerApp] Serving notebooks from local directory: /home/mihirban/llments
[I 2024-04-19 16:07:05.343 ServerApp] Jupyter Server 2.13.0 is running at:
[I 2024-04-19 16:07:05.343 ServerApp] http://babel-2-12:8888/tree?token=7518be047ac17af444f8303ca5d7a4ec1d8cbeff7aa4d953
[I 2024-04-19 16:07:05.343 ServerApp]     http://127.0.0.1:8888/tree?token=7518be047ac17af444f8303ca5d7a4ec1d8cbeff7aa4d953
[I 2024-04-19 16:07:05.343 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-04-19 16:07:05.346 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/mihirban/.local/share/jupyter/runtime/jpserver-1107012-open.html
    Or copy and paste one of these URLs:
        http://babel-2-12:8888/tree?token=7518be047ac17af444f8303ca5d7a4ec1d8cbeff7aa4d953
        http://127.0.0.1:8888/tree?token=7518be047ac17af444f8303ca5d7a4ec1d8cbeff7aa4d953
[I 2024-04-19 16:07:05.369 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-04-19 16:15:45.287 ServerApp] 404 GET /hub/api (@172.16.1.2) 350.81ms referer=None
[I 2024-04-19 16:15:45.290 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.34ms
[W 2024-04-19 16:15:47.204 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.81ms referer=None
[I 2024-04-19 16:15:47.206 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.24ms
[W 2024-04-19 16:16:08.567 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.89ms referer=None
[I 2024-04-19 16:16:08.569 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.23ms
[I 2024-04-19 16:16:08.605 ServerApp] Kernel started: 84ca2771-cf3b-47d1-b782-041a5e401556
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-04-19 16:16:09.728 ServerApp] Connecting to kernel 84ca2771-cf3b-47d1-b782-041a5e401556.
[W 2024-04-19 16:16:09.897 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.901 ServerApp] 403 GET /api/kernelspecs?1713557769871 (@172.16.1.2) 4.64ms referer=None
[W 2024-04-19 16:16:09.902 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.903 ServerApp] 403 GET /api/kernels?1713557769872 (@172.16.1.2) 1.14ms referer=None
[W 2024-04-19 16:16:09.905 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.62ms referer=None
[W 2024-04-19 16:16:09.906 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.93ms referer=None
[W 2024-04-19 16:16:09.906 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.907 ServerApp] 403 GET /api/kernels?1713557769887 (@172.16.1.2) 1.32ms referer=None
[W 2024-04-19 16:16:09.907 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.907 ServerApp] 403 GET /api/sessions?1713557769888 (@172.16.1.2) 1.69ms referer=None
[W 2024-04-19 16:16:09.940 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.940 ServerApp] 403 GET /api/kernelspecs?1713557769903 (@172.16.1.2) 0.52ms referer=None
[I 2024-04-19 16:16:09.954 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.24ms
[I 2024-04-19 16:16:09.955 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.53ms
[W 2024-04-19 16:16:09.955 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.87ms referer=None
[W 2024-04-19 16:16:09.974 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.974 ServerApp] 403 GET /api/kernelspecs?1713557769954 (@172.16.1.2) 0.52ms referer=None
[W 2024-04-19 16:16:09.975 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.975 ServerApp] 403 GET /api/kernels?1713557769955 (@172.16.1.2) 0.50ms referer=None
[W 2024-04-19 16:16:09.984 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.984 ServerApp] 403 GET /api/kernels?1713557769961 (@172.16.1.2) 0.53ms referer=None
[W 2024-04-19 16:16:09.985 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.985 ServerApp] 403 GET /api/sessions?1713557769961 (@172.16.1.2) 0.51ms referer=None
[W 2024-04-19 16:16:09.998 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:09.999 ServerApp] 403 GET /api/kernelspecs?1713557769964 (@172.16.1.2) 0.51ms referer=None
[W 2024-04-19 16:16:09.999 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.000 ServerApp] 403 GET /api/kernels?1713557769964 (@172.16.1.2) 0.80ms referer=None
[I 2024-04-19 16:16:10.000 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.87ms
[W 2024-04-19 16:16:10.000 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.000 ServerApp] 403 GET /api/kernels?1713557769967 (@172.16.1.2) 1.21ms referer=None
[W 2024-04-19 16:16:10.001 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.001 ServerApp] 403 GET /api/sessions?1713557769968 (@172.16.1.2) 1.55ms referer=None
[W 2024-04-19 16:16:10.014 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.50ms referer=None
[W 2024-04-19 16:16:10.015 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.64ms referer=None
[W 2024-04-19 16:16:10.015 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.016 ServerApp] 403 GET /api/kernelspecs?1713557770001 (@172.16.1.2) 1.38ms referer=None
[W 2024-04-19 16:16:10.016 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.016 ServerApp] 403 GET /api/kernels?1713557770002 (@172.16.1.2) 1.28ms referer=None
[W 2024-04-19 16:16:10.016 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.017 ServerApp] 403 GET /api/kernelspecs?1713557770009 (@172.16.1.2) 1.61ms referer=None
[W 2024-04-19 16:16:10.017 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.017 ServerApp] 403 GET /api/kernels?1713557770009 (@172.16.1.2) 1.94ms referer=None
[W 2024-04-19 16:16:10.017 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.018 ServerApp] 403 GET /api/sessions?1713557770010 (@172.16.1.2) 2.28ms referer=None
[I 2024-04-19 16:16:10.018 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.28ms
[I 2024-04-19 16:16:10.019 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.20ms
[W 2024-04-19 16:16:10.023 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.024 ServerApp] 403 GET /api/kernelspecs?1713557770016 (@172.16.1.2) 0.49ms referer=None
[W 2024-04-19 16:16:10.029 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.030 ServerApp] 403 GET /api/kernelspecs?1713557770022 (@172.16.1.2) 0.50ms referer=None
[W 2024-04-19 16:16:10.030 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.030 ServerApp] 403 GET /api/kernels?1713557770022 (@172.16.1.2) 0.51ms referer=None
[W 2024-04-19 16:16:10.031 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.031 ServerApp] 403 GET /api/kernels?1713557770023 (@172.16.1.2) 0.69ms referer=None
[W 2024-04-19 16:16:10.031 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.032 ServerApp] 403 GET /api/sessions?1713557770027 (@172.16.1.2) 0.98ms referer=None
[W 2024-04-19 16:16:10.032 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.033 ServerApp] 403 GET /api/sessions?1713557770024 (@172.16.1.2) 0.81ms referer=None
[W 2024-04-19 16:16:10.033 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.033 ServerApp] 403 GET /api/kernelspecs?1713557770025 (@172.16.1.2) 1.14ms referer=None
[W 2024-04-19 16:16:10.033 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.034 ServerApp] 403 GET /api/kernels?1713557770026 (@172.16.1.2) 1.48ms referer=None
[W 2024-04-19 16:16:10.034 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.034 ServerApp] 403 GET /api/kernels?1713557770026 (@172.16.1.2) 1.80ms referer=None
[W 2024-04-19 16:16:10.034 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.035 ServerApp] 403 GET /api/kernelspecs?1713557770030 (@172.16.1.2) 0.56ms referer=None
[W 2024-04-19 16:16:10.036 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 16:16:10.037 ServerApp] 403 GET /api/kernelspecs?1713557770033 (@172.16.1.2) 0.48ms referer=None
[W 2024-04-19 16:16:12.374 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.1.2) 0.72ms referer=None
[W 2024-04-19 16:16:12.374 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.47ms referer=None
[I 2024-04-19 16:16:12.376 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.23ms
[W 2024-04-19 16:16:12.378 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.1.2) 0.49ms referer=None
[I 2024-04-19 16:23:14.594 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2024-04-19 16:23:14.596 ServerApp] kernel 84ca2771-cf3b-47d1-b782-041a5e401556 restarted
[I 2024-04-19 16:23:14.602 ServerApp] Starting buffering for 84ca2771-cf3b-47d1-b782-041a5e401556:c7f15cbc-832b-4f9f-9cc0-84b53607009c
[I 2024-04-19 16:23:14.616 ServerApp] Connecting to kernel 84ca2771-cf3b-47d1-b782-041a5e401556.
[I 2024-04-19 16:23:14.616 ServerApp] Restoring connection for 84ca2771-cf3b-47d1-b782-041a5e401556:c7f15cbc-832b-4f9f-9cc0-84b53607009c
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-04-19 18:52:08.370 ServerApp] Starting buffering for 84ca2771-cf3b-47d1-b782-041a5e401556:c7f15cbc-832b-4f9f-9cc0-84b53607009c
[W 2024-04-19 18:52:10.384 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.96ms referer=None
[W 2024-04-19 18:52:10.388 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.48ms referer=None
[I 2024-04-19 18:52:10.433 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.26ms
[I 2024-04-19 18:52:10.445 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.17ms
[W 2024-04-19 18:52:10.485 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.486 ServerApp] 403 GET /api/kernelspecs?1713567130442 (@172.16.1.2) 1.15ms referer=None
[W 2024-04-19 18:52:10.486 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.486 ServerApp] 403 GET /api/kernels?1713567130443 (@172.16.1.2) 0.47ms referer=None
[W 2024-04-19 18:52:10.488 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.488 ServerApp] 403 GET /api/kernels?1713567130459 (@172.16.1.2) 0.49ms referer=None
[W 2024-04-19 18:52:10.489 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.489 ServerApp] 403 GET /api/sessions?1713567130459 (@172.16.1.2) 0.49ms referer=None
[W 2024-04-19 18:52:10.491 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.492 ServerApp] 403 GET /api/kernelspecs?1713567130475 (@172.16.1.2) 0.45ms referer=None
[W 2024-04-19 18:52:10.492 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.493 ServerApp] 403 GET /api/kernels?1713567130477 (@172.16.1.2) 0.74ms referer=None
[W 2024-04-19 18:52:10.493 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.493 ServerApp] 403 GET /api/kernels?1713567130479 (@172.16.1.2) 1.07ms referer=None
[W 2024-04-19 18:52:10.493 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.494 ServerApp] 403 GET /api/sessions?1713567130479 (@172.16.1.2) 1.43ms referer=None
[W 2024-04-19 18:52:10.519 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.519 ServerApp] 403 GET /api/kernelspecs?1713567130492 (@172.16.1.2) 0.44ms referer=None
[W 2024-04-19 18:52:10.520 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.44ms referer=None
[W 2024-04-19 18:52:10.521 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.521 ServerApp] 403 GET /api/kernelspecs?1713567130504 (@172.16.1.2) 0.42ms referer=None
[W 2024-04-19 18:52:10.526 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.44ms referer=None
[I 2024-04-19 18:52:10.528 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.18ms
[I 2024-04-19 18:52:10.532 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.17ms
[W 2024-04-19 18:52:10.532 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.533 ServerApp] 403 GET /api/sessions?1713567130531 (@172.16.1.2) 0.73ms referer=None
[W 2024-04-19 18:52:10.533 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.533 ServerApp] 403 GET /api/kernelspecs?1713567130529 (@172.16.1.2) 0.95ms referer=None
[W 2024-04-19 18:52:10.533 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.534 ServerApp] 403 GET /api/kernels?1713567130529 (@172.16.1.2) 1.27ms referer=None
[W 2024-04-19 18:52:10.534 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.534 ServerApp] 403 GET /api/kernels?1713567130530 (@172.16.1.2) 0.45ms referer=None
[W 2024-04-19 18:52:10.538 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.538 ServerApp] 403 GET /api/kernelspecs?1713567130532 (@172.16.1.2) 0.52ms referer=None
[W 2024-04-19 18:52:10.539 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.539 ServerApp] 403 GET /api/kernels?1713567130533 (@172.16.1.2) 0.49ms referer=None
[W 2024-04-19 18:52:10.539 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.540 ServerApp] 403 GET /api/kernels?1713567130533 (@172.16.1.2) 0.52ms referer=None
[W 2024-04-19 18:52:10.540 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.540 ServerApp] 403 GET /api/sessions?1713567130534 (@172.16.1.2) 0.43ms referer=None
[W 2024-04-19 18:52:10.541 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:10.541 ServerApp] 403 GET /api/kernelspecs?1713567130539 (@172.16.1.2) 0.41ms referer=None
[W 2024-04-19 18:52:15.987 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.61ms referer=None
[W 2024-04-19 18:52:15.988 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.61ms referer=None
[I 2024-04-19 18:52:16.021 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.20ms
[I 2024-04-19 18:52:16.023 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.18ms
[W 2024-04-19 18:52:16.051 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.051 ServerApp] 403 GET /api/kernelspecs?1713567136033 (@172.16.1.2) 0.56ms referer=None
[W 2024-04-19 18:52:16.052 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.052 ServerApp] 403 GET /api/kernels?1713567136033 (@172.16.1.2) 0.60ms referer=None
[W 2024-04-19 18:52:16.052 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.053 ServerApp] 403 GET /api/kernelspecs?1713567136036 (@172.16.1.2) 0.63ms referer=None
[W 2024-04-19 18:52:16.053 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.053 ServerApp] 403 GET /api/kernels?1713567136037 (@172.16.1.2) 0.91ms referer=None
[W 2024-04-19 18:52:16.054 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.054 ServerApp] 403 GET /api/sessions?1713567136041 (@172.16.1.2) 0.75ms referer=None
[W 2024-04-19 18:52:16.054 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.054 ServerApp] 403 GET /api/kernels?1713567136039 (@172.16.1.2) 1.03ms referer=None
[W 2024-04-19 18:52:16.054 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.055 ServerApp] 403 GET /api/sessions?1713567136040 (@172.16.1.2) 1.35ms referer=None
[W 2024-04-19 18:52:16.055 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.055 ServerApp] 403 GET /api/kernels?1713567136040 (@172.16.1.2) 1.64ms referer=None
[W 2024-04-19 18:52:16.101 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.75ms referer=None
[W 2024-04-19 18:52:16.102 ServerApp] 404 GET /hub/api (@172.16.1.2) 0.73ms referer=None
[I 2024-04-19 18:52:16.107 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.18ms
[I 2024-04-19 18:52:16.111 JupyterNotebookApp] 302 GET /tree? (@172.16.1.2) 0.17ms
[W 2024-04-19 18:52:16.122 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.123 ServerApp] 403 GET /api/kernelspecs?1713567136112 (@172.16.1.2) 0.46ms referer=None
[W 2024-04-19 18:52:16.123 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.123 ServerApp] 403 GET /api/kernels?1713567136113 (@172.16.1.2) 0.45ms referer=None
[W 2024-04-19 18:52:16.124 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.124 ServerApp] 403 GET /api/kernels?1713567136114 (@172.16.1.2) 0.55ms referer=None
[W 2024-04-19 18:52:16.125 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.125 ServerApp] 403 GET /api/sessions?1713567136115 (@172.16.1.2) 0.75ms referer=None
[W 2024-04-19 18:52:16.125 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.125 ServerApp] 403 GET /api/kernelspecs?1713567136117 (@172.16.1.2) 1.04ms referer=None
[W 2024-04-19 18:52:16.125 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.126 ServerApp] 403 GET /api/kernels?1713567136118 (@172.16.1.2) 1.35ms referer=None
[W 2024-04-19 18:52:16.126 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.126 ServerApp] 403 GET /api/kernels?1713567136120 (@172.16.1.2) 1.64ms referer=None
[W 2024-04-19 18:52:16.126 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.127 ServerApp] 403 GET /api/sessions?1713567136120 (@172.16.1.2) 0.54ms referer=None
[W 2024-04-19 18:52:16.150 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.151 ServerApp] 403 GET /api/kernelspecs?1713567136124 (@172.16.1.2) 0.64ms referer=None
[W 2024-04-19 18:52:16.154 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-19 18:52:16.154 ServerApp] 403 GET /api/kernelspecs?1713567136141 (@172.16.1.2) 0.42ms referer=None
[W 2024-04-20 11:35:35.325 ServerApp] 404 GET /hub/api (@172.16.1.3) 4.05ms referer=None
[W 2024-04-20 11:35:35.326 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.42ms referer=None
[W 2024-04-20 11:35:35.330 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.40ms referer=None
[I 2024-04-20 11:35:35.426 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.46ms
[I 2024-04-20 11:35:35.427 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.45ms
[I 2024-04-20 11:35:35.427 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.19ms
[W 2024-04-20 11:35:35.595 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.596 ServerApp] 403 GET /api/kernelspecs?1713627335432 (@172.16.1.3) 1.27ms referer=None
[W 2024-04-20 11:35:35.596 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.597 ServerApp] 403 GET /api/kernels?1713627335432 (@172.16.1.3) 0.55ms referer=None
[W 2024-04-20 11:35:35.597 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.597 ServerApp] 403 GET /api/kernelspecs?1713627335434 (@172.16.1.3) 0.54ms referer=None
[W 2024-04-20 11:35:35.597 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.598 ServerApp] 403 GET /api/kernels?1713627335435 (@172.16.1.3) 0.83ms referer=None
[W 2024-04-20 11:35:35.600 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.600 ServerApp] 403 GET /api/kernels?1713627335577 (@172.16.1.3) 0.50ms referer=None
[W 2024-04-20 11:35:35.601 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.601 ServerApp] 403 GET /api/sessions?1713627335577 (@172.16.1.3) 0.70ms referer=None
[W 2024-04-20 11:35:35.601 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.601 ServerApp] 403 GET /api/kernels?1713627335578 (@172.16.1.3) 1.03ms referer=None
[W 2024-04-20 11:35:35.601 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.602 ServerApp] 403 GET /api/sessions?1713627335579 (@172.16.1.3) 1.36ms referer=None
[W 2024-04-20 11:35:35.741 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.741 ServerApp] 403 GET /api/kernelspecs?1713627335630 (@172.16.1.3) 0.48ms referer=None
[W 2024-04-20 11:35:35.781 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:35.781 ServerApp] 403 GET /api/kernelspecs?1713627335630 (@172.16.1.3) 0.77ms referer=None
[W 2024-04-20 11:35:35.782 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.44ms referer=None
[W 2024-04-20 11:35:35.782 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.44ms referer=None
[I 2024-04-20 11:35:35.862 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.22ms
[I 2024-04-20 11:35:35.862 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.21ms
[W 2024-04-20 11:35:35.999 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:36.000 ServerApp] 403 GET /api/kernelspecs?1713627335908 (@172.16.1.3) 0.57ms referer=None
[W 2024-04-20 11:35:36.000 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:36.000 ServerApp] 403 GET /api/kernels?1713627335909 (@172.16.1.3) 0.47ms referer=None
[W 2024-04-20 11:35:36.001 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:36.001 ServerApp] 403 GET /api/kernels?1713627335910 (@172.16.1.3) 0.53ms referer=None
[W 2024-04-20 11:35:36.001 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:36.001 ServerApp] 403 GET /api/sessions?1713627335911 (@172.16.1.3) 0.84ms referer=None
[W 2024-04-20 11:35:36.014 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:36.014 ServerApp] 403 GET /api/kernelspecs?1713627335944 (@172.16.1.3) 0.47ms referer=None
[W 2024-04-20 11:35:36.014 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:36.015 ServerApp] 403 GET /api/kernels?1713627335945 (@172.16.1.3) 0.63ms referer=None
[W 2024-04-20 11:35:36.015 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:36.015 ServerApp] 403 GET /api/kernels?1713627335946 (@172.16.1.3) 0.91ms referer=None
[W 2024-04-20 11:35:36.015 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:36.015 ServerApp] 403 GET /api/sessions?1713627335947 (@172.16.1.3) 1.22ms referer=None
[W 2024-04-20 11:35:36.097 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:35:36.097 ServerApp] 403 GET /api/kernelspecs?1713627336049 (@172.16.1.3) 0.47ms referer=None
[W 2024-04-20 11:36:45.471 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.53ms referer=None
[W 2024-04-20 11:36:45.474 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.41ms referer=None
[I 2024-04-20 11:36:45.509 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.19ms
[I 2024-04-20 11:36:45.510 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.16ms
[W 2024-04-20 11:36:45.552 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.552 ServerApp] 403 GET /api/kernelspecs?1713627405514 (@172.16.1.3) 0.98ms referer=None
[W 2024-04-20 11:36:45.553 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.553 ServerApp] 403 GET /api/kernels?1713627405514 (@172.16.1.3) 0.46ms referer=None
[W 2024-04-20 11:36:45.553 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.554 ServerApp] 403 GET /api/kernelspecs?1713627405516 (@172.16.1.3) 0.53ms referer=None
[W 2024-04-20 11:36:45.554 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.554 ServerApp] 403 GET /api/kernels?1713627405517 (@172.16.1.3) 0.81ms referer=None
[W 2024-04-20 11:36:45.558 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.558 ServerApp] 403 GET /api/kernels?1713627405532 (@172.16.1.3) 0.45ms referer=None
[W 2024-04-20 11:36:45.558 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.559 ServerApp] 403 GET /api/sessions?1713627405533 (@172.16.1.3) 0.45ms referer=None
[W 2024-04-20 11:36:45.559 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.559 ServerApp] 403 GET /api/kernels?1713627405534 (@172.16.1.3) 0.51ms referer=None
[W 2024-04-20 11:36:45.559 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.560 ServerApp] 403 GET /api/sessions?1713627405535 (@172.16.1.3) 0.81ms referer=None
[W 2024-04-20 11:36:45.600 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.600 ServerApp] 403 GET /api/kernelspecs?1713627405578 (@172.16.1.3) 0.62ms referer=None
[W 2024-04-20 11:36:45.600 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.601 ServerApp] 403 GET /api/kernelspecs?1713627405579 (@172.16.1.3) 0.61ms referer=None
[W 2024-04-20 11:36:45.601 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.90ms referer=None
[W 2024-04-20 11:36:45.601 ServerApp] 404 GET /hub/api (@172.16.1.3) 1.18ms referer=None
[I 2024-04-20 11:36:45.612 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.20ms
[I 2024-04-20 11:36:45.612 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.20ms
[W 2024-04-20 11:36:45.620 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.620 ServerApp] 403 GET /api/kernelspecs?1713627405614 (@172.16.1.3) 0.67ms referer=None
[W 2024-04-20 11:36:45.620 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.621 ServerApp] 403 GET /api/kernels?1713627405614 (@172.16.1.3) 1.03ms referer=None
[W 2024-04-20 11:36:45.621 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.621 ServerApp] 403 GET /api/kernels?1713627405615 (@172.16.1.3) 0.51ms referer=None
[W 2024-04-20 11:36:45.622 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.622 ServerApp] 403 GET /api/sessions?1713627405615 (@172.16.1.3) 0.56ms referer=None
[W 2024-04-20 11:36:45.622 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.622 ServerApp] 403 GET /api/kernelspecs?1713627405617 (@172.16.1.3) 0.84ms referer=None
[W 2024-04-20 11:36:45.623 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.623 ServerApp] 403 GET /api/kernels?1713627405617 (@172.16.1.3) 0.57ms referer=None
[W 2024-04-20 11:36:45.623 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.623 ServerApp] 403 GET /api/kernels?1713627405618 (@172.16.1.3) 0.87ms referer=None
[W 2024-04-20 11:36:45.624 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.624 ServerApp] 403 GET /api/sessions?1713627405619 (@172.16.1.3) 0.45ms referer=None
[W 2024-04-20 11:36:45.627 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.628 ServerApp] 403 GET /api/kernelspecs?1713627405624 (@172.16.1.3) 0.43ms referer=None
[W 2024-04-20 11:36:45.628 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:45.628 ServerApp] 403 GET /api/kernelspecs?1713627405627 (@172.16.1.3) 0.41ms referer=None
[W 2024-04-20 11:36:47.228 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.80ms referer=None
[W 2024-04-20 11:36:47.233 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.42ms referer=None
[I 2024-04-20 11:36:47.260 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.19ms
[I 2024-04-20 11:36:47.261 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.18ms
[W 2024-04-20 11:36:47.283 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.283 ServerApp] 403 GET /api/kernelspecs?1713627407271 (@172.16.1.3) 0.49ms referer=None
[W 2024-04-20 11:36:47.283 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.283 ServerApp] 403 GET /api/kernels?1713627407271 (@172.16.1.3) 0.48ms referer=None
[W 2024-04-20 11:36:47.284 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.284 ServerApp] 403 GET /api/kernelspecs?1713627407275 (@172.16.1.3) 0.51ms referer=None
[W 2024-04-20 11:36:47.285 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.285 ServerApp] 403 GET /api/kernels?1713627407275 (@172.16.1.3) 0.64ms referer=None
[W 2024-04-20 11:36:47.285 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.285 ServerApp] 403 GET /api/sessions?1713627407279 (@172.16.1.3) 0.90ms referer=None
[W 2024-04-20 11:36:47.285 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.286 ServerApp] 403 GET /api/kernels?1713627407277 (@172.16.1.3) 0.46ms referer=None
[W 2024-04-20 11:36:47.286 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.286 ServerApp] 403 GET /api/sessions?1713627407278 (@172.16.1.3) 0.54ms referer=None
[W 2024-04-20 11:36:47.286 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.287 ServerApp] 403 GET /api/kernels?1713627407278 (@172.16.1.3) 0.82ms referer=None
[W 2024-04-20 11:36:47.311 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.311 ServerApp] 403 GET /api/kernelspecs?1713627407294 (@172.16.1.3) 0.43ms referer=None
[W 2024-04-20 11:36:47.316 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.42ms referer=None
[W 2024-04-20 11:36:47.317 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.41ms referer=None
[I 2024-04-20 11:36:47.319 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.17ms
[I 2024-04-20 11:36:47.320 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.16ms
[W 2024-04-20 11:36:47.327 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.327 ServerApp] 403 GET /api/kernelspecs?1713627407322 (@172.16.1.3) 0.61ms referer=None
[W 2024-04-20 11:36:47.327 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.328 ServerApp] 403 GET /api/kernels?1713627407322 (@172.16.1.3) 0.96ms referer=None
[W 2024-04-20 11:36:47.328 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.328 ServerApp] 403 GET /api/kernels?1713627407323 (@172.16.1.3) 0.57ms referer=None
[W 2024-04-20 11:36:47.329 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.329 ServerApp] 403 GET /api/sessions?1713627407326 (@172.16.1.3) 0.49ms referer=None
[W 2024-04-20 11:36:47.330 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.330 ServerApp] 403 GET /api/sessions?1713627407323 (@172.16.1.3) 0.74ms referer=None
[W 2024-04-20 11:36:47.330 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.330 ServerApp] 403 GET /api/kernelspecs?1713627407325 (@172.16.1.3) 1.02ms referer=None
[W 2024-04-20 11:36:47.330 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.331 ServerApp] 403 GET /api/kernels?1713627407325 (@172.16.1.3) 1.32ms referer=None
[W 2024-04-20 11:36:47.331 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.331 ServerApp] 403 GET /api/kernels?1713627407326 (@172.16.1.3) 1.59ms referer=None
[W 2024-04-20 11:36:47.331 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.332 ServerApp] 403 GET /api/kernelspecs?1713627407329 (@172.16.1.3) 0.50ms referer=None
[W 2024-04-20 11:36:47.333 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 11:36:47.334 ServerApp] 403 GET /api/kernelspecs?1713627407332 (@172.16.1.3) 0.41ms referer=None
[W 2024-04-20 13:45:06.550 ServerApp] 404 GET /hub/api (@172.16.1.3) 1.30ms referer=None
[W 2024-04-20 13:45:06.560 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.46ms referer=None
[I 2024-04-20 13:45:06.643 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.20ms
[I 2024-04-20 13:45:06.652 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.18ms
[W 2024-04-20 13:45:06.670 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.671 ServerApp] 403 GET /api/kernelspecs?1713635106645 (@172.16.1.3) 1.01ms referer=None
[W 2024-04-20 13:45:06.671 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.672 ServerApp] 403 GET /api/kernels?1713635106646 (@172.16.1.3) 0.49ms referer=None
[W 2024-04-20 13:45:06.673 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.674 ServerApp] 403 GET /api/kernels?1713635106660 (@172.16.1.3) 0.43ms referer=None
[W 2024-04-20 13:45:06.674 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.674 ServerApp] 403 GET /api/sessions?1713635106661 (@172.16.1.3) 0.49ms referer=None
[W 2024-04-20 13:45:06.676 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.676 ServerApp] 403 GET /api/kernelspecs?1713635106664 (@172.16.1.3) 0.46ms referer=None
[W 2024-04-20 13:45:06.676 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.677 ServerApp] 403 GET /api/kernels?1713635106664 (@172.16.1.3) 0.59ms referer=None
[W 2024-04-20 13:45:06.677 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.677 ServerApp] 403 GET /api/kernels?1713635106667 (@172.16.1.3) 0.90ms referer=None
[W 2024-04-20 13:45:06.683 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.683 ServerApp] 403 GET /api/sessions?1713635106668 (@172.16.1.3) 0.41ms referer=None
[W 2024-04-20 13:45:06.707 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.707 ServerApp] 403 GET /api/kernelspecs?1713635106676 (@172.16.1.3) 0.48ms referer=None
[W 2024-04-20 13:45:06.708 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.46ms referer=None
[W 2024-04-20 13:45:06.709 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.709 ServerApp] 403 GET /api/kernelspecs?1713635106692 (@172.16.1.3) 0.41ms referer=None
[W 2024-04-20 13:45:06.716 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.46ms referer=None
[I 2024-04-20 13:45:06.716 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.35ms
[I 2024-04-20 13:45:06.720 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.21ms
[W 2024-04-20 13:45:06.721 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.722 ServerApp] 403 GET /api/kernelspecs?1713635106717 (@172.16.1.3) 1.04ms referer=None
[W 2024-04-20 13:45:06.722 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.722 ServerApp] 403 GET /api/kernels?1713635106718 (@172.16.1.3) 1.32ms referer=None
[W 2024-04-20 13:45:06.722 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.723 ServerApp] 403 GET /api/sessions?1713635106719 (@172.16.1.3) 1.60ms referer=None
[W 2024-04-20 13:45:06.723 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.723 ServerApp] 403 GET /api/kernels?1713635106718 (@172.16.1.3) 1.84ms referer=None
[W 2024-04-20 13:45:06.730 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.731 ServerApp] 403 GET /api/kernelspecs?1713635106721 (@172.16.1.3) 0.43ms referer=None
[W 2024-04-20 13:45:06.731 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.731 ServerApp] 403 GET /api/kernels?1713635106722 (@172.16.1.3) 0.49ms referer=None
[W 2024-04-20 13:45:06.732 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.732 ServerApp] 403 GET /api/kernels?1713635106722 (@172.16.1.3) 0.51ms referer=None
[W 2024-04-20 13:45:06.732 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.732 ServerApp] 403 GET /api/sessions?1713635106723 (@172.16.1.3) 0.49ms referer=None
[W 2024-04-20 13:45:06.734 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:45:06.734 ServerApp] 403 GET /api/kernelspecs?1713635106731 (@172.16.1.3) 0.47ms referer=None
[W 2024-04-20 13:47:25.348 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.83ms referer=None
[W 2024-04-20 13:47:25.351 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.52ms referer=None
[I 2024-04-20 13:47:25.381 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.20ms
[I 2024-04-20 13:47:25.385 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.18ms
[W 2024-04-20 13:47:25.404 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.404 ServerApp] 403 GET /api/kernelspecs?1713635245382 (@172.16.1.3) 1.13ms referer=None
[W 2024-04-20 13:47:25.405 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.405 ServerApp] 403 GET /api/kernels?1713635245383 (@172.16.1.3) 1.46ms referer=None
[W 2024-04-20 13:47:25.407 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.407 ServerApp] 403 GET /api/kernels?1713635245393 (@172.16.1.3) 0.42ms referer=None
[W 2024-04-20 13:47:25.408 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.408 ServerApp] 403 GET /api/sessions?1713635245394 (@172.16.1.3) 0.48ms referer=None
[W 2024-04-20 13:47:25.409 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.409 ServerApp] 403 GET /api/kernelspecs?1713635245397 (@172.16.1.3) 0.46ms referer=None
[W 2024-04-20 13:47:25.410 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.410 ServerApp] 403 GET /api/kernels?1713635245397 (@172.16.1.3) 0.47ms referer=None
[W 2024-04-20 13:47:25.410 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.411 ServerApp] 403 GET /api/kernels?1713635245401 (@172.16.1.3) 0.47ms referer=None
[W 2024-04-20 13:47:25.411 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.411 ServerApp] 403 GET /api/sessions?1713635245401 (@172.16.1.3) 0.41ms referer=None
[W 2024-04-20 13:47:25.436 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.436 ServerApp] 403 GET /api/kernelspecs?1713635245409 (@172.16.1.3) 0.50ms referer=None
[W 2024-04-20 13:47:25.437 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.48ms referer=None
[W 2024-04-20 13:47:25.440 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.440 ServerApp] 403 GET /api/kernelspecs?1713635245422 (@172.16.1.3) 0.42ms referer=None
[W 2024-04-20 13:47:25.451 ServerApp] 404 GET /hub/api (@172.16.1.3) 0.46ms referer=None
[I 2024-04-20 13:47:25.452 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.18ms
[I 2024-04-20 13:47:25.463 JupyterNotebookApp] 302 GET /tree? (@172.16.1.3) 0.17ms
[W 2024-04-20 13:47:25.463 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.464 ServerApp] 403 GET /api/kernelspecs?1713635245455 (@172.16.1.3) 0.67ms referer=None
[W 2024-04-20 13:47:25.464 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.464 ServerApp] 403 GET /api/kernels?1713635245456 (@172.16.1.3) 1.01ms referer=None
[W 2024-04-20 13:47:25.464 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.464 ServerApp] 403 GET /api/kernels?1713635245457 (@172.16.1.3) 1.36ms referer=None
[W 2024-04-20 13:47:25.465 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.465 ServerApp] 403 GET /api/sessions?1713635245459 (@172.16.1.3) 0.46ms referer=None
[W 2024-04-20 13:47:25.474 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.475 ServerApp] 403 GET /api/kernelspecs?1713635245465 (@172.16.1.3) 0.52ms referer=None
[W 2024-04-20 13:47:25.475 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.475 ServerApp] 403 GET /api/kernels?1713635245466 (@172.16.1.3) 0.53ms referer=None
[W 2024-04-20 13:47:25.476 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.476 ServerApp] 403 GET /api/kernels?1713635245468 (@172.16.1.3) 0.58ms referer=None
[W 2024-04-20 13:47:25.476 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.477 ServerApp] 403 GET /api/sessions?1713635245469 (@172.16.1.3) 0.92ms referer=None
[W 2024-04-20 13:47:25.477 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.477 ServerApp] 403 GET /api/kernelspecs?1713635245470 (@172.16.1.3) 0.45ms referer=None
[W 2024-04-20 13:47:25.481 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/mihirban/miniconda3/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 13:47:25.482 ServerApp] 403 GET /api/kernelspecs?1713635245476 (@172.16.1.3) 0.72ms referer=None
slurmstepd: error: *** JOB 238794 ON babel-2-12 CANCELLED AT 2024-04-20T16:07:10 DUE TO TIME LIMIT ***
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=238794.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
